#!/bin/bash

#
# convbzr2git - Recoding bzr-repository to git.
#
# Process is:
#   - make checkout bazaar-repositiry from src to work (target) dir,
#   - update bazaar repository to first revision
#   - and commited this revision into git.
#   - copy .bzrignore into .gitignore & add on it ".bzr" line
#       on each loop pass.
# Repeate this operation sequentially.
#
# Copy .bzrignore into .gitignore & add on it ".bzr" line   on each loop pass.
# Commit message & date are extracted from bzr repository with "log" command
# & stored into tmp file 'msg' & 'ti.me' respectively.
# Field 'commit author' is not extracted - now I'm is not needed in this.
#
# Author: Solomatov A.A (aso)
# Date:   Sun Oct 19 15:09:27 2014 +0400
# License: GPL v.3
#

# limit of passes: all number of commits in bazaar-repository 
lim=4
#lim=51
# Source directory with bazaar repository
src='/etc'
# Target directory, in which the work will take place 
#work='etckeeper'
work='/root/prj/etckeeper'


tmprefx='/tmp'

echo "Entering work directory . . ." >&2
echo -n "working directory is: " >&2
pushd $work >&2
echo >&2

#bzr co -r 1 $srs .
git init

for ((a=1; a<$lim+1; a++)) ; do
  echo rev... $a >&2
  bzr up -r $a
  cp .bzrignore .gitignore
  echo >> .gitignore
  echo ".bzr" >> .gitignore
  bzr log -r $a | tail -n +7 > "$tmprefx/msg"
  bzr log -r $a | head -n 5 | tail -n 1 | sed -e 's/timestamp: [^ ]\{,4\} //' > "$tmprefx/ti.me"
  git add -A .
#  sleep 4
  sleep 2
  git commit -F "$tmprefx/msg" --date="{$(cat "$tmprefx/ti.me")}"
#  sleep 3
  sleep 1
  #git commit -F ../msg --date="$(echo ../ti.me)" --dry-run
done
rm -f "$tmprefx/msg"
rm -f "$tmprefx/ti.me"

echo >&2
echo "Leave work directory . . . " >&2
echo -n "return to directory: " >&2
popd >&2

