#!/bin/bash

lim=10
#lim=51
src='/etc'
targetdir='etckeeper'

#echo -n "Entering work directory: $(pushd $targetdir) . . ." >&2
echo "Entering work directory . . ." >&2
echo -n "working directory is: " >&2
pushd $targetdir >&2
echo >&2

#bzr co -r 1 $srs .

for ((a=1; a<$lim+1; a++)) ; do
  echo rev... $a >&2
  bzr log -r $a | head -n 5 | tail -n 1
#  bzr log -r $a | tail -n +5 > ../time.mk
done

#echo -n "Leave work directory: $(popd) . . ." >&2
echo >&2
echo "Leave work directory . . . " >&2
echo -n "return to directory: " >&2
popd >&2
